language: ruby
sudo: false
cache: bundler
script:
  - bundle exec rake
after_success:
  - '[ -d coverage ] && bundle exec codeclimate-test-reporter'
rvm:
  - ruby-head
  - 2.3.0
  - 2.2
  - 2.1
  - 2.0
  - jruby
  - jruby-9.1.5.0
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
