language: ruby
sudo: false
cache: bundler
rvm:
  - ruby-head
  - 2.2
  - 2.1
  - 2.0
  - 1.9.3
  - jruby
  - jruby-head
  - jruby-19mode # JRuby in 1.9 mode
env:
  global:
    - CODECLIMATE_REPO_TOKEN=d4c34cd6f4f50eb092a1f01e1b7e24acb0b9c59b266dfc91bcd26df15a48b8f5
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
